/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardPostsCreateRouteImport } from './routes/dashboard/posts/create'
import { Route as DashboardPostsPostSlugEditRouteImport } from './routes/dashboard/posts/$postSlug.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsCreateRoute = DashboardPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsPostSlugEditRoute =
  DashboardPostsPostSlugEditRouteImport.update({
    id: '/posts/$postSlug/edit',
    path: '/posts/$postSlug/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/create': typeof DashboardPostsCreateRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/posts/$postSlug/edit': typeof DashboardPostsPostSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/posts/create': typeof DashboardPostsCreateRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/posts/$postSlug/edit': typeof DashboardPostsPostSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/create': typeof DashboardPostsCreateRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/posts/$postSlug/edit': typeof DashboardPostsPostSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/posts/create'
    | '/dashboard/posts'
    | '/dashboard/users'
    | '/dashboard/posts/$postSlug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/profile'
    | '/dashboard'
    | '/dashboard/posts/create'
    | '/dashboard/posts'
    | '/dashboard/users'
    | '/dashboard/posts/$postSlug/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/posts/create'
    | '/dashboard/posts/'
    | '/dashboard/users/'
    | '/dashboard/posts/$postSlug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/create': {
      id: '/dashboard/posts/create'
      path: '/posts/create'
      fullPath: '/dashboard/posts/create'
      preLoaderRoute: typeof DashboardPostsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/$postSlug/edit': {
      id: '/dashboard/posts/$postSlug/edit'
      path: '/posts/$postSlug/edit'
      fullPath: '/dashboard/posts/$postSlug/edit'
      preLoaderRoute: typeof DashboardPostsPostSlugEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPostsCreateRoute: typeof DashboardPostsCreateRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardPostsPostSlugEditRoute: typeof DashboardPostsPostSlugEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPostsCreateRoute: DashboardPostsCreateRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardPostsPostSlugEditRoute: DashboardPostsPostSlugEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
